### ISSUE TITLE
Characters are moveable before the countdown timer ends.

### ISSUE THREAD

**Issue by APODICTIC** [Sturdge/Splash-Dash#108] opened 2020-03-16 16:08 UTC
Name of bug: Characters can move when paused before countdown ends and then resuming the game.

Date:16/3/2020

Type: Moderate

Repeatable: Yes

Steps to reproduce:  1. Start the game
                                      2. Select the characters
                                      3. Pause the game before countdown occurs.
                                      4. Try moving the characters during the countdown after resuming the game

Screenshot: 

![image](https://user-images.githubusercontent.com/56399859/76777610-5c593580-67a0-11ea-9d7f-effbf5e9d77f.png)

Description: Characters movement aren’t locked whenever a player pauses the game and resumes it before the countdown gets over.

**Comment by Sturdge** [comment] 2020-03-21 19:20
The cause was the variable "isTimingDown" being set to "true" when the pause menu was exited.

Fixed by removing that and not allowing the players to pause during the countdown.

**Closed as completed by Sturdge** 2020-03-21 19:20 UTC
Labels: bug
